import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { getGlobalPageData } from "@/http/http";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getGlobalPageData();
  const { layouts } = globalData;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header data={layouts[0]} />
        {children}
        <Footer data={layouts[1]} />
      </body>
    </html>
  );
}
